# Build stage
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
#-----Melhora na otimização--------- 
# Copia csproj e faz restore (cache de dependências)
COPY *.csproj ./
RUN dotnet restore
#--------------------------------------
# Copia o resto do código e faz publish
COPY . .
RUN dotnet publish "Produtor.csproj" -c Release -o /publish

# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /publish .
ENTRYPOINT ["dotnet", "Produtor.dll"]
